package nl.knokko.customitems.particle;

import static nl.knokko.customitems.MCVersions.*;

import nl.knokko.customitems.NameHelper;
public enum CIParticle {

	EXPLOSION_NORMAL(VERSION1_12),
	EXPLOSION_LARGE(VERSION1_12),
	EXPLOSION_HUGE(VERSION1_12),
	FIREWORKS_SPARK(VERSION1_12),
	WATER_BUBBLE(VERSION1_12),
	WATER_SPLASH(VERSION1_12),
	WATER_WAKE(VERSION1_12),
	SUSPENDED(VERSION1_12),
	SUSPENDED_DEPTH(VERSION1_12),
	CRIT(VERSION1_12),
	CRIT_MAGIC(VERSION1_12),
	SMOKE_NORMAL(VERSION1_12),
	SMOKE_LARGE(VERSION1_12),
	SPELL(VERSION1_12),
	SPELL_INSTANT(VERSION1_12),
	SPELL_MOB(VERSION1_12),
	SPELL_MOB_AMBIENT(VERSION1_12),
	SPELL_WITCH(VERSION1_12),
	DRIP_WATER(VERSION1_12),
	DRIP_LAVA(VERSION1_12),
	VILLAGER_ANGRY(VERSION1_12),
	VILLAGER_HAPPY(VERSION1_12),
	TOWN_AURA(VERSION1_12),
	NOTE(VERSION1_12),
	PORTAL(VERSION1_12),
	ENCHANTMENT_TABLE(VERSION1_12),
	FLAME(VERSION1_12),
	LAVA(VERSION1_12),
	FOOTSTEP(VERSION1_12),
	CLOUD(VERSION1_12),
	REDSTONE(VERSION1_12),
	SNOWBALL(VERSION1_12),
	SNOW_SHOVEL(VERSION1_12),
	SLIME(VERSION1_12),
	HEART(VERSION1_12),
	BARRIER(VERSION1_12),
	ITEM_CRACK(VERSION1_12),
	BLOCK_CRACK(VERSION1_12),
	BLOCK_DUST(VERSION1_12),
	WATER_DROP(VERSION1_12),
	ITEM_TAKE(VERSION1_12),
	MOB_APPEARANCE(VERSION1_12),
	DRAGON_BREATH(VERSION1_12),
	END_ROD(VERSION1_12),
	DAMAGE_INDICATOR(VERSION1_12),
	SWEEP_ATTACK(VERSION1_12),
	FALLING_DUST(VERSION1_12),
	TOTEM(VERSION1_12),
	SPIT(VERSION1_12),
	
	SQUID_INK(VERSION1_13),
	BUBBLE_POP(VERSION1_13),
	CURRENT_DOWN(VERSION1_13),
	BUBBLE_COLUMN_UP(VERSION1_13),
	NAUTILUS(VERSION1_13),
	DOLPHIN(VERSION1_13),
	COMPOSTER(VERSION1_13),
	FLASH(VERSION1_13),
	FALLING_LAVA(VERSION1_13),
	LANDING_LAVA(VERSION1_13),
	FALLING_WATER(VERSION1_13),
	LEGACY_BLOCK_CRACK(VERSION1_13),
	LEGACY_BLOCK_DUST(VERSION1_13),
	LEGACY_FALLING_DUST(VERSION1_13),
	
	SNEEZE(VERSION1_14),
	CAMPFIRE_COSY_SMOKE(VERSION1_14),
	CAMPFIRE_SIGNAL_SMOKE(VERSION1_14);
	
	public final int mcVersion;

	CIParticle(int mcVersion){
		this.mcVersion = mcVersion;
	}
	
	@Override
	public String toString() {
		return NameHelper.getNiceEnumName(name(), mcVersion);
	}
}
