name: CustomItems
main: nl.knokko.customitems.plugin.CustomItemsPlugin
version: 6.2
depend: [KnokkoCore]
softdepend: [CrazyEnchantments]
loadbefore: [UltraChest]
commands:
  customitems:
    description: give a custom item to a player
    useage: /ci give <item name> [player name]
    aliases: [ci]